---
title: "Customer Lifetime Value"
author: "Saqib Ali"
date: "June 5, 2017"
output:
  pdf_document: default
  html_document: defaultam music online. In addition to a monthly subscription fee, *Spotifoo* allows its customers to purchase products and services mentioned using the *Spotifoo* app. Some customers make no additional purchase besides the monthly subscriptions fee. Other make regular purchases.  

---

You work as an analyst for *Spotifoo*, an online music streaming service. Spotifoo charges its customers a low fixed rate to stre
Management wants to:

1. understand who their best customers are.
2. create a customer lifetime value (CLV) model that predict the lifetime value of each customer after their first month on the *Spotifoo* service.


The data assets are available to you are:
- user attributes (demographics, locations, customer survey responses, etc.)
- purchase history (items purchases, date/time of purchase, purchase amount, etc.) and, 
- product attributes (product, product type, etc.) 

For each management question, describe your process. In particular, describe:
- the response you would use for your model,
- what predictors you would use,
- what errors you will use,
- how you get a training and test data set, 
- the modeling techniques you would use

# Who Are *Spotifoo*'s best customers?
The Best Customers are who SPEND the most in purchasing addition items

# Customer Lifetime Value
## Response Variable / Dependent Variable
The response will be Catogerical Variable of the Binned [Sum of [item purchased * the cost of the item]]. For e.g. Total Spend > 100 = Excellent; Total Spend > 50 < 100 = Good etc. 

## Predictors
The predictors to use in this Model would be the Demographics of the Customer, Location

## Model Selection
With our Response Variable being a Categorical Variable this is Classification Problem. I would start with a Logistic Regression and compare the results with KNN, Random Forest and GLM
